/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 43
#define LARGE_STATE_COUNT 11
#define SYMBOL_COUNT 38
#define ALIAS_COUNT 1
#define TOKEN_COUNT 22
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym__newline = 1,
  sym_comment = 2,
  anon_sym_hello = 3,
  sym_escaped = 4,
  sym__string_content = 5,
  anon_sym_DQUOTE = 6,
  anon_sym_true = 7,
  anon_sym_false = 8,
  sym_int = 9,
  anon_sym_DOTinf = 10,
  anon_sym_PLUS_DOTinf = 11,
  anon_sym_DASH_DOTinf = 12,
  aux_sym_float_token1 = 13,
  aux_sym_float_token2 = 14,
  anon_sym_COMMA = 15,
  anon_sym_LBRACK = 16,
  anon_sym_RBRACK = 17,
  sym_bare_key = 18,
  anon_sym_EQ = 19,
  anon_sym_LBRACE = 20,
  anon_sym_RBRACE = 21,
  sym_config = 22,
  sym__statement = 23,
  sym_string = 24,
  sym_bool = 25,
  sym_float = 26,
  sym__seq_value = 27,
  sym_seq = 28,
  sym_tagged = 29,
  sym__value = 30,
  sym_tagged_key = 31,
  sym__key = 32,
  sym_kv = 33,
  sym_map = 34,
  aux_sym_config_repeat1 = 35,
  aux_sym_string_repeat1 = 36,
  aux_sym_seq_repeat1 = 37,
  alias_sym_quoted_key = 38,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym__newline] = "_newline",
  [sym_comment] = "comment",
  [anon_sym_hello] = "hello",
  [sym_escaped] = "escaped",
  [sym__string_content] = "_string_content",
  [anon_sym_DQUOTE] = "\"",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_int] = "int",
  [anon_sym_DOTinf] = ".inf",
  [anon_sym_PLUS_DOTinf] = "+.inf",
  [anon_sym_DASH_DOTinf] = "-.inf",
  [aux_sym_float_token1] = "float_token1",
  [aux_sym_float_token2] = "float_token2",
  [anon_sym_COMMA] = ",",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym_bare_key] = "bare_key",
  [anon_sym_EQ] = "=",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_config] = "config",
  [sym__statement] = "_statement",
  [sym_string] = "string",
  [sym_bool] = "bool",
  [sym_float] = "float",
  [sym__seq_value] = "_seq_value",
  [sym_seq] = "seq",
  [sym_tagged] = "tagged",
  [sym__value] = "_value",
  [sym_tagged_key] = "tagged",
  [sym__key] = "_key",
  [sym_kv] = "kv",
  [sym_map] = "map",
  [aux_sym_config_repeat1] = "config_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
  [aux_sym_seq_repeat1] = "seq_repeat1",
  [alias_sym_quoted_key] = "quoted_key",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym__newline] = sym__newline,
  [sym_comment] = sym_comment,
  [anon_sym_hello] = anon_sym_hello,
  [sym_escaped] = sym_escaped,
  [sym__string_content] = sym__string_content,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_int] = sym_int,
  [anon_sym_DOTinf] = anon_sym_DOTinf,
  [anon_sym_PLUS_DOTinf] = anon_sym_PLUS_DOTinf,
  [anon_sym_DASH_DOTinf] = anon_sym_DASH_DOTinf,
  [aux_sym_float_token1] = aux_sym_float_token1,
  [aux_sym_float_token2] = aux_sym_float_token2,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_bare_key] = sym_bare_key,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_config] = sym_config,
  [sym__statement] = sym__statement,
  [sym_string] = sym_string,
  [sym_bool] = sym_bool,
  [sym_float] = sym_float,
  [sym__seq_value] = sym__seq_value,
  [sym_seq] = sym_seq,
  [sym_tagged] = sym_tagged,
  [sym__value] = sym__value,
  [sym_tagged_key] = sym_tagged,
  [sym__key] = sym__key,
  [sym_kv] = sym_kv,
  [sym_map] = sym_map,
  [aux_sym_config_repeat1] = aux_sym_config_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
  [aux_sym_seq_repeat1] = aux_sym_seq_repeat1,
  [alias_sym_quoted_key] = alias_sym_quoted_key,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_hello] = {
    .visible = true,
    .named = false,
  },
  [sym_escaped] = {
    .visible = true,
    .named = true,
  },
  [sym__string_content] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_int] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOTinf] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS_DOTinf] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_DOTinf] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_float_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_float_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_bare_key] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_config] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_bool] = {
    .visible = true,
    .named = true,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [sym__seq_value] = {
    .visible = false,
    .named = true,
  },
  [sym_seq] = {
    .visible = true,
    .named = true,
  },
  [sym_tagged] = {
    .visible = true,
    .named = true,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
  },
  [sym_tagged_key] = {
    .visible = true,
    .named = true,
  },
  [sym__key] = {
    .visible = false,
    .named = true,
  },
  [sym_kv] = {
    .visible = true,
    .named = true,
  },
  [sym_map] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_config_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_seq_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_quoted_key] = {
    .visible = true,
    .named = true,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [0] = alias_sym_quoted_key,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  sym_string, 2,
    sym_string,
    alias_sym_quoted_key,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 3,
  [7] = 2,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 17,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 15,
  [26] = 12,
  [27] = 20,
  [28] = 13,
  [29] = 14,
  [30] = 16,
  [31] = 21,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 35,
  [38] = 34,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(32);
      ADVANCE_MAP(
        '\n', 33,
        '"', 40,
        '#', 34,
        '+', 3,
        ',', 50,
        '-', 4,
        '.', 12,
        '=', 58,
        '[', 51,
        '\\', 29,
        ']', 52,
        'f', 5,
        'h', 8,
        't', 22,
        '{', 59,
        '}', 60,
      );
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(30);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(43);
      END_STATE();
    case 1:
      if (lookahead == ' ') ADVANCE(38);
      if (lookahead == '"') ADVANCE(40);
      if (lookahead == '#') ADVANCE(39);
      if (lookahead == '\\') ADVANCE(29);
      if (lookahead == '\t' ||
          lookahead == '\r') SKIP(2);
      if (lookahead > ' ' &&
          lookahead != 0x7f) ADVANCE(39);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(40);
      if (lookahead == '#') ADVANCE(34);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2);
      END_STATE();
    case 3:
      if (lookahead == '.') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(43);
      END_STATE();
    case 4:
      if (lookahead == '.') ADVANCE(14);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(43);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(15);
      END_STATE();
    case 6:
      if (lookahead == 'e') ADVANCE(41);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(42);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(17);
      END_STATE();
    case 9:
      if (lookahead == 'f') ADVANCE(44);
      END_STATE();
    case 10:
      if (lookahead == 'f') ADVANCE(45);
      END_STATE();
    case 11:
      if (lookahead == 'f') ADVANCE(46);
      END_STATE();
    case 12:
      if (lookahead == 'i') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(48);
      END_STATE();
    case 13:
      if (lookahead == 'i') ADVANCE(19);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(48);
      END_STATE();
    case 14:
      if (lookahead == 'i') ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(48);
      END_STATE();
    case 15:
      if (lookahead == 'l') ADVANCE(23);
      END_STATE();
    case 16:
      if (lookahead == 'l') ADVANCE(21);
      END_STATE();
    case 17:
      if (lookahead == 'l') ADVANCE(16);
      END_STATE();
    case 18:
      if (lookahead == 'n') ADVANCE(9);
      END_STATE();
    case 19:
      if (lookahead == 'n') ADVANCE(10);
      END_STATE();
    case 20:
      if (lookahead == 'n') ADVANCE(11);
      END_STATE();
    case 21:
      if (lookahead == 'o') ADVANCE(35);
      END_STATE();
    case 22:
      if (lookahead == 'r') ADVANCE(24);
      END_STATE();
    case 23:
      if (lookahead == 's') ADVANCE(7);
      END_STATE();
    case 24:
      if (lookahead == 'u') ADVANCE(6);
      END_STATE();
    case 25:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(47);
      END_STATE();
    case 26:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(49);
      END_STATE();
    case 27:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(47);
      END_STATE();
    case 28:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(49);
      END_STATE();
    case 29:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    case 30:
      if (eof) ADVANCE(32);
      ADVANCE_MAP(
        '\n', 33,
        '"', 40,
        '#', 34,
        '+', 3,
        ',', 50,
        '-', 4,
        '.', 12,
        '=', 58,
        '[', 51,
        ']', 52,
        'f', 5,
        'h', 8,
        't', 22,
        '{', 59,
        '}', 60,
      );
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(30);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(43);
      END_STATE();
    case 31:
      if (eof) ADVANCE(32);
      ADVANCE_MAP(
        '\n', 33,
        '"', 40,
        '#', 34,
        '+', 3,
        '-', 4,
        '.', 12,
        '[', 51,
        'h', 53,
        '}', 60,
      );
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(31);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(43);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym__newline);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_hello);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_hello);
      if (lookahead == '+' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_escaped);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym__string_content);
      if (lookahead == ' ') ADVANCE(38);
      if (lookahead == '#') ADVANCE(39);
      if (lookahead > ' ' &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '\\' &&
          lookahead != 0x7f) ADVANCE(39);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym__string_content);
      if (lookahead > 0x1f &&
          lookahead != '"' &&
          lookahead != '\\' &&
          lookahead != 0x7f) ADVANCE(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_int);
      if (lookahead == '.') ADVANCE(48);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(43);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_DOTinf);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_PLUS_DOTinf);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_DASH_DOTinf);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym_float_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(aux_sym_float_token2);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(26);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(48);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(aux_sym_float_token2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(49);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_bare_key);
      if (lookahead == 'e') ADVANCE(55);
      if (lookahead == '+' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_bare_key);
      if (lookahead == 'l') ADVANCE(56);
      if (lookahead == '+' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_bare_key);
      if (lookahead == 'l') ADVANCE(54);
      if (lookahead == '+' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_bare_key);
      if (lookahead == 'o') ADVANCE(36);
      if (lookahead == '+' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_bare_key);
      if (lookahead == '+' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 31},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 31},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 31},
  [9] = {.lex_state = 31},
  [10] = {.lex_state = 31},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 31},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 31},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 31},
  [23] = {.lex_state = 31},
  [24] = {.lex_state = 31},
  [25] = {.lex_state = 31},
  [26] = {.lex_state = 31},
  [27] = {.lex_state = 31},
  [28] = {.lex_state = 31},
  [29] = {.lex_state = 31},
  [30] = {.lex_state = 31},
  [31] = {.lex_state = 31},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym__newline] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_hello] = ACTIONS(1),
    [sym_escaped] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_int] = ACTIONS(1),
    [anon_sym_DOTinf] = ACTIONS(1),
    [anon_sym_PLUS_DOTinf] = ACTIONS(1),
    [anon_sym_DASH_DOTinf] = ACTIONS(1),
    [aux_sym_float_token1] = ACTIONS(1),
    [aux_sym_float_token2] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_config] = STATE(42),
    [sym__statement] = STATE(9),
    [sym_string] = STATE(36),
    [sym_float] = STATE(39),
    [sym_seq] = STATE(39),
    [sym_tagged_key] = STATE(39),
    [sym__key] = STATE(39),
    [sym_kv] = STATE(9),
    [aux_sym_config_repeat1] = STATE(9),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym__newline] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
    [anon_sym_hello] = ACTIONS(9),
    [anon_sym_DQUOTE] = ACTIONS(11),
    [sym_int] = ACTIONS(13),
    [anon_sym_DOTinf] = ACTIONS(15),
    [anon_sym_PLUS_DOTinf] = ACTIONS(15),
    [anon_sym_DASH_DOTinf] = ACTIONS(15),
    [aux_sym_float_token1] = ACTIONS(15),
    [aux_sym_float_token2] = ACTIONS(15),
    [anon_sym_LBRACK] = ACTIONS(17),
    [sym_bare_key] = ACTIONS(19),
  },
  [STATE(2)] = {
    [sym_string] = STATE(18),
    [sym_bool] = STATE(4),
    [sym_float] = STATE(4),
    [sym__seq_value] = STATE(4),
    [sym_seq] = STATE(4),
    [sym_tagged] = STATE(4),
    [sym__value] = STATE(4),
    [aux_sym_seq_repeat1] = STATE(4),
    [sym__newline] = ACTIONS(21),
    [sym_comment] = ACTIONS(3),
    [anon_sym_DQUOTE] = ACTIONS(11),
    [anon_sym_true] = ACTIONS(23),
    [anon_sym_false] = ACTIONS(23),
    [sym_int] = ACTIONS(25),
    [anon_sym_DOTinf] = ACTIONS(15),
    [anon_sym_PLUS_DOTinf] = ACTIONS(15),
    [anon_sym_DASH_DOTinf] = ACTIONS(15),
    [aux_sym_float_token1] = ACTIONS(15),
    [aux_sym_float_token2] = ACTIONS(15),
    [anon_sym_COMMA] = ACTIONS(21),
    [anon_sym_LBRACK] = ACTIONS(17),
    [anon_sym_RBRACK] = ACTIONS(27),
  },
  [STATE(3)] = {
    [sym_string] = STATE(18),
    [sym_bool] = STATE(2),
    [sym_float] = STATE(2),
    [sym__seq_value] = STATE(2),
    [sym_seq] = STATE(2),
    [sym_tagged] = STATE(2),
    [sym__value] = STATE(2),
    [aux_sym_seq_repeat1] = STATE(2),
    [sym__newline] = ACTIONS(29),
    [sym_comment] = ACTIONS(3),
    [anon_sym_DQUOTE] = ACTIONS(11),
    [anon_sym_true] = ACTIONS(23),
    [anon_sym_false] = ACTIONS(23),
    [sym_int] = ACTIONS(31),
    [anon_sym_DOTinf] = ACTIONS(15),
    [anon_sym_PLUS_DOTinf] = ACTIONS(15),
    [anon_sym_DASH_DOTinf] = ACTIONS(15),
    [aux_sym_float_token1] = ACTIONS(15),
    [aux_sym_float_token2] = ACTIONS(15),
    [anon_sym_COMMA] = ACTIONS(29),
    [anon_sym_LBRACK] = ACTIONS(17),
    [anon_sym_RBRACK] = ACTIONS(33),
  },
  [STATE(4)] = {
    [sym_string] = STATE(18),
    [sym_bool] = STATE(4),
    [sym_float] = STATE(4),
    [sym__seq_value] = STATE(4),
    [sym_seq] = STATE(4),
    [sym_tagged] = STATE(4),
    [sym__value] = STATE(4),
    [aux_sym_seq_repeat1] = STATE(4),
    [sym__newline] = ACTIONS(35),
    [sym_comment] = ACTIONS(3),
    [anon_sym_DQUOTE] = ACTIONS(38),
    [anon_sym_true] = ACTIONS(41),
    [anon_sym_false] = ACTIONS(41),
    [sym_int] = ACTIONS(44),
    [anon_sym_DOTinf] = ACTIONS(47),
    [anon_sym_PLUS_DOTinf] = ACTIONS(47),
    [anon_sym_DASH_DOTinf] = ACTIONS(47),
    [aux_sym_float_token1] = ACTIONS(47),
    [aux_sym_float_token2] = ACTIONS(47),
    [anon_sym_COMMA] = ACTIONS(35),
    [anon_sym_LBRACK] = ACTIONS(50),
    [anon_sym_RBRACK] = ACTIONS(53),
  },
  [STATE(5)] = {
    [sym__statement] = STATE(5),
    [sym_string] = STATE(36),
    [sym_float] = STATE(39),
    [sym_seq] = STATE(39),
    [sym_tagged_key] = STATE(39),
    [sym__key] = STATE(39),
    [sym_kv] = STATE(5),
    [aux_sym_config_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(55),
    [sym__newline] = ACTIONS(57),
    [sym_comment] = ACTIONS(3),
    [anon_sym_hello] = ACTIONS(60),
    [anon_sym_DQUOTE] = ACTIONS(63),
    [sym_int] = ACTIONS(66),
    [anon_sym_DOTinf] = ACTIONS(69),
    [anon_sym_PLUS_DOTinf] = ACTIONS(69),
    [anon_sym_DASH_DOTinf] = ACTIONS(69),
    [aux_sym_float_token1] = ACTIONS(69),
    [aux_sym_float_token2] = ACTIONS(69),
    [anon_sym_LBRACK] = ACTIONS(72),
    [sym_bare_key] = ACTIONS(75),
    [anon_sym_RBRACE] = ACTIONS(55),
  },
  [STATE(6)] = {
    [sym_string] = STATE(18),
    [sym_bool] = STATE(7),
    [sym_float] = STATE(7),
    [sym__seq_value] = STATE(7),
    [sym_seq] = STATE(7),
    [sym_tagged] = STATE(7),
    [sym__value] = STATE(7),
    [aux_sym_seq_repeat1] = STATE(7),
    [sym__newline] = ACTIONS(78),
    [sym_comment] = ACTIONS(3),
    [anon_sym_DQUOTE] = ACTIONS(11),
    [anon_sym_true] = ACTIONS(23),
    [anon_sym_false] = ACTIONS(23),
    [sym_int] = ACTIONS(80),
    [anon_sym_DOTinf] = ACTIONS(15),
    [anon_sym_PLUS_DOTinf] = ACTIONS(15),
    [anon_sym_DASH_DOTinf] = ACTIONS(15),
    [aux_sym_float_token1] = ACTIONS(15),
    [aux_sym_float_token2] = ACTIONS(15),
    [anon_sym_COMMA] = ACTIONS(78),
    [anon_sym_LBRACK] = ACTIONS(17),
    [anon_sym_RBRACK] = ACTIONS(82),
  },
  [STATE(7)] = {
    [sym_string] = STATE(18),
    [sym_bool] = STATE(4),
    [sym_float] = STATE(4),
    [sym__seq_value] = STATE(4),
    [sym_seq] = STATE(4),
    [sym_tagged] = STATE(4),
    [sym__value] = STATE(4),
    [aux_sym_seq_repeat1] = STATE(4),
    [sym__newline] = ACTIONS(21),
    [sym_comment] = ACTIONS(3),
    [anon_sym_DQUOTE] = ACTIONS(11),
    [anon_sym_true] = ACTIONS(23),
    [anon_sym_false] = ACTIONS(23),
    [sym_int] = ACTIONS(25),
    [anon_sym_DOTinf] = ACTIONS(15),
    [anon_sym_PLUS_DOTinf] = ACTIONS(15),
    [anon_sym_DASH_DOTinf] = ACTIONS(15),
    [aux_sym_float_token1] = ACTIONS(15),
    [aux_sym_float_token2] = ACTIONS(15),
    [anon_sym_COMMA] = ACTIONS(21),
    [anon_sym_LBRACK] = ACTIONS(17),
    [anon_sym_RBRACK] = ACTIONS(84),
  },
  [STATE(8)] = {
    [sym__statement] = STATE(10),
    [sym_string] = STATE(36),
    [sym_float] = STATE(39),
    [sym_seq] = STATE(39),
    [sym_tagged_key] = STATE(39),
    [sym__key] = STATE(39),
    [sym_kv] = STATE(10),
    [aux_sym_config_repeat1] = STATE(10),
    [sym__newline] = ACTIONS(86),
    [sym_comment] = ACTIONS(3),
    [anon_sym_hello] = ACTIONS(88),
    [anon_sym_DQUOTE] = ACTIONS(11),
    [sym_int] = ACTIONS(13),
    [anon_sym_DOTinf] = ACTIONS(15),
    [anon_sym_PLUS_DOTinf] = ACTIONS(15),
    [anon_sym_DASH_DOTinf] = ACTIONS(15),
    [aux_sym_float_token1] = ACTIONS(15),
    [aux_sym_float_token2] = ACTIONS(15),
    [anon_sym_LBRACK] = ACTIONS(17),
    [sym_bare_key] = ACTIONS(19),
    [anon_sym_RBRACE] = ACTIONS(90),
  },
  [STATE(9)] = {
    [sym__statement] = STATE(5),
    [sym_string] = STATE(36),
    [sym_float] = STATE(39),
    [sym_seq] = STATE(39),
    [sym_tagged_key] = STATE(39),
    [sym__key] = STATE(39),
    [sym_kv] = STATE(5),
    [aux_sym_config_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(92),
    [sym__newline] = ACTIONS(94),
    [sym_comment] = ACTIONS(3),
    [anon_sym_hello] = ACTIONS(96),
    [anon_sym_DQUOTE] = ACTIONS(11),
    [sym_int] = ACTIONS(13),
    [anon_sym_DOTinf] = ACTIONS(15),
    [anon_sym_PLUS_DOTinf] = ACTIONS(15),
    [anon_sym_DASH_DOTinf] = ACTIONS(15),
    [aux_sym_float_token1] = ACTIONS(15),
    [aux_sym_float_token2] = ACTIONS(15),
    [anon_sym_LBRACK] = ACTIONS(17),
    [sym_bare_key] = ACTIONS(19),
  },
  [STATE(10)] = {
    [sym__statement] = STATE(5),
    [sym_string] = STATE(36),
    [sym_float] = STATE(39),
    [sym_seq] = STATE(39),
    [sym_tagged_key] = STATE(39),
    [sym__key] = STATE(39),
    [sym_kv] = STATE(5),
    [aux_sym_config_repeat1] = STATE(5),
    [sym__newline] = ACTIONS(94),
    [sym_comment] = ACTIONS(3),
    [anon_sym_hello] = ACTIONS(96),
    [anon_sym_DQUOTE] = ACTIONS(11),
    [sym_int] = ACTIONS(13),
    [anon_sym_DOTinf] = ACTIONS(15),
    [anon_sym_PLUS_DOTinf] = ACTIONS(15),
    [anon_sym_DASH_DOTinf] = ACTIONS(15),
    [aux_sym_float_token1] = ACTIONS(15),
    [aux_sym_float_token2] = ACTIONS(15),
    [anon_sym_LBRACK] = ACTIONS(17),
    [sym_bare_key] = ACTIONS(19),
    [anon_sym_RBRACE] = ACTIONS(98),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(100), 1,
      anon_sym_DQUOTE,
    ACTIONS(104), 1,
      sym_int,
    ACTIONS(108), 1,
      anon_sym_LBRACK,
    ACTIONS(110), 1,
      anon_sym_LBRACE,
    STATE(17), 1,
      sym_string,
    ACTIONS(102), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(106), 5,
      anon_sym_DOTinf,
      anon_sym_PLUS_DOTinf,
      anon_sym_DASH_DOTinf,
      aux_sym_float_token1,
      aux_sym_float_token2,
    STATE(22), 6,
      sym_bool,
      sym_float,
      sym_seq,
      sym_tagged,
      sym__value,
      sym_map,
  [38] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(114), 1,
      sym_int,
    ACTIONS(112), 14,
      sym__newline,
      anon_sym_DQUOTE,
      anon_sym_true,
      anon_sym_false,
      anon_sym_DOTinf,
      anon_sym_PLUS_DOTinf,
      anon_sym_DASH_DOTinf,
      aux_sym_float_token1,
      aux_sym_float_token2,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_EQ,
      anon_sym_LBRACE,
  [61] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(118), 1,
      sym_int,
    ACTIONS(116), 14,
      sym__newline,
      anon_sym_DQUOTE,
      anon_sym_true,
      anon_sym_false,
      anon_sym_DOTinf,
      anon_sym_PLUS_DOTinf,
      anon_sym_DASH_DOTinf,
      aux_sym_float_token1,
      aux_sym_float_token2,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_EQ,
      anon_sym_LBRACE,
  [84] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(122), 1,
      sym_int,
    ACTIONS(120), 14,
      sym__newline,
      anon_sym_DQUOTE,
      anon_sym_true,
      anon_sym_false,
      anon_sym_DOTinf,
      anon_sym_PLUS_DOTinf,
      anon_sym_DASH_DOTinf,
      aux_sym_float_token1,
      aux_sym_float_token2,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_EQ,
      anon_sym_LBRACE,
  [107] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(126), 1,
      sym_int,
    ACTIONS(124), 14,
      sym__newline,
      anon_sym_DQUOTE,
      anon_sym_true,
      anon_sym_false,
      anon_sym_DOTinf,
      anon_sym_PLUS_DOTinf,
      anon_sym_DASH_DOTinf,
      aux_sym_float_token1,
      aux_sym_float_token2,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_EQ,
      anon_sym_LBRACE,
  [130] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(130), 1,
      sym_int,
    ACTIONS(128), 14,
      sym__newline,
      anon_sym_DQUOTE,
      anon_sym_true,
      anon_sym_false,
      anon_sym_DOTinf,
      anon_sym_PLUS_DOTinf,
      anon_sym_DASH_DOTinf,
      aux_sym_float_token1,
      aux_sym_float_token2,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_EQ,
      anon_sym_LBRACE,
  [153] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(108), 1,
      anon_sym_LBRACK,
    STATE(31), 1,
      sym_seq,
    ACTIONS(134), 3,
      anon_sym_hello,
      sym_int,
      sym_bare_key,
    ACTIONS(132), 9,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_DQUOTE,
      anon_sym_DOTinf,
      anon_sym_PLUS_DOTinf,
      anon_sym_DASH_DOTinf,
      aux_sym_float_token1,
      aux_sym_float_token2,
      anon_sym_RBRACE,
  [179] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(134), 1,
      sym_int,
    STATE(21), 1,
      sym_seq,
    ACTIONS(132), 11,
      sym__newline,
      anon_sym_DQUOTE,
      anon_sym_true,
      anon_sym_false,
      anon_sym_DOTinf,
      anon_sym_PLUS_DOTinf,
      anon_sym_DASH_DOTinf,
      aux_sym_float_token1,
      aux_sym_float_token2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [205] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(138), 3,
      anon_sym_hello,
      sym_int,
      sym_bare_key,
    ACTIONS(136), 10,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_DQUOTE,
      anon_sym_DOTinf,
      anon_sym_PLUS_DOTinf,
      anon_sym_DASH_DOTinf,
      aux_sym_float_token1,
      aux_sym_float_token2,
      anon_sym_LBRACK,
      anon_sym_RBRACE,
  [226] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(142), 1,
      sym_int,
    ACTIONS(140), 12,
      sym__newline,
      anon_sym_DQUOTE,
      anon_sym_true,
      anon_sym_false,
      anon_sym_DOTinf,
      anon_sym_PLUS_DOTinf,
      anon_sym_DASH_DOTinf,
      aux_sym_float_token1,
      aux_sym_float_token2,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [247] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(146), 1,
      sym_int,
    ACTIONS(144), 12,
      sym__newline,
      anon_sym_DQUOTE,
      anon_sym_true,
      anon_sym_false,
      anon_sym_DOTinf,
      anon_sym_PLUS_DOTinf,
      anon_sym_DASH_DOTinf,
      aux_sym_float_token1,
      aux_sym_float_token2,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [268] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(150), 3,
      anon_sym_hello,
      sym_int,
      sym_bare_key,
    ACTIONS(148), 10,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_DQUOTE,
      anon_sym_DOTinf,
      anon_sym_PLUS_DOTinf,
      anon_sym_DASH_DOTinf,
      aux_sym_float_token1,
      aux_sym_float_token2,
      anon_sym_LBRACK,
      anon_sym_RBRACE,
  [289] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(154), 3,
      anon_sym_hello,
      sym_int,
      sym_bare_key,
    ACTIONS(152), 10,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_DQUOTE,
      anon_sym_DOTinf,
      anon_sym_PLUS_DOTinf,
      anon_sym_DASH_DOTinf,
      aux_sym_float_token1,
      aux_sym_float_token2,
      anon_sym_LBRACK,
      anon_sym_RBRACE,
  [310] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(158), 3,
      anon_sym_hello,
      sym_int,
      sym_bare_key,
    ACTIONS(156), 10,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_DQUOTE,
      anon_sym_DOTinf,
      anon_sym_PLUS_DOTinf,
      anon_sym_DASH_DOTinf,
      aux_sym_float_token1,
      aux_sym_float_token2,
      anon_sym_LBRACK,
      anon_sym_RBRACE,
  [331] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(126), 3,
      anon_sym_hello,
      sym_int,
      sym_bare_key,
    ACTIONS(124), 10,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_DQUOTE,
      anon_sym_DOTinf,
      anon_sym_PLUS_DOTinf,
      anon_sym_DASH_DOTinf,
      aux_sym_float_token1,
      aux_sym_float_token2,
      anon_sym_LBRACK,
      anon_sym_RBRACE,
  [352] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(114), 3,
      anon_sym_hello,
      sym_int,
      sym_bare_key,
    ACTIONS(112), 10,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_DQUOTE,
      anon_sym_DOTinf,
      anon_sym_PLUS_DOTinf,
      anon_sym_DASH_DOTinf,
      aux_sym_float_token1,
      aux_sym_float_token2,
      anon_sym_LBRACK,
      anon_sym_RBRACE,
  [373] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(142), 3,
      anon_sym_hello,
      sym_int,
      sym_bare_key,
    ACTIONS(140), 10,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_DQUOTE,
      anon_sym_DOTinf,
      anon_sym_PLUS_DOTinf,
      anon_sym_DASH_DOTinf,
      aux_sym_float_token1,
      aux_sym_float_token2,
      anon_sym_LBRACK,
      anon_sym_RBRACE,
  [394] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(118), 3,
      anon_sym_hello,
      sym_int,
      sym_bare_key,
    ACTIONS(116), 10,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_DQUOTE,
      anon_sym_DOTinf,
      anon_sym_PLUS_DOTinf,
      anon_sym_DASH_DOTinf,
      aux_sym_float_token1,
      aux_sym_float_token2,
      anon_sym_LBRACK,
      anon_sym_RBRACE,
  [415] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(122), 3,
      anon_sym_hello,
      sym_int,
      sym_bare_key,
    ACTIONS(120), 10,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_DQUOTE,
      anon_sym_DOTinf,
      anon_sym_PLUS_DOTinf,
      anon_sym_DASH_DOTinf,
      aux_sym_float_token1,
      aux_sym_float_token2,
      anon_sym_LBRACK,
      anon_sym_RBRACE,
  [436] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(130), 3,
      anon_sym_hello,
      sym_int,
      sym_bare_key,
    ACTIONS(128), 10,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_DQUOTE,
      anon_sym_DOTinf,
      anon_sym_PLUS_DOTinf,
      anon_sym_DASH_DOTinf,
      aux_sym_float_token1,
      aux_sym_float_token2,
      anon_sym_LBRACK,
      anon_sym_RBRACE,
  [457] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(146), 3,
      anon_sym_hello,
      sym_int,
      sym_bare_key,
    ACTIONS(144), 10,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_DQUOTE,
      anon_sym_DOTinf,
      anon_sym_PLUS_DOTinf,
      anon_sym_DASH_DOTinf,
      aux_sym_float_token1,
      aux_sym_float_token2,
      anon_sym_LBRACK,
      anon_sym_RBRACE,
  [478] = 4,
    ACTIONS(160), 1,
      sym_comment,
    ACTIONS(165), 1,
      anon_sym_DQUOTE,
    STATE(32), 1,
      aux_sym_string_repeat1,
    ACTIONS(162), 2,
      sym_escaped,
      sym__string_content,
  [492] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    STATE(40), 1,
      sym_seq,
    ACTIONS(167), 2,
      anon_sym_EQ,
      anon_sym_LBRACE,
  [506] = 4,
    ACTIONS(160), 1,
      sym_comment,
    ACTIONS(171), 1,
      anon_sym_DQUOTE,
    STATE(32), 1,
      aux_sym_string_repeat1,
    ACTIONS(169), 2,
      sym_escaped,
      sym__string_content,
  [520] = 4,
    ACTIONS(160), 1,
      sym_comment,
    ACTIONS(175), 1,
      anon_sym_DQUOTE,
    STATE(34), 1,
      aux_sym_string_repeat1,
    ACTIONS(173), 2,
      sym_escaped,
      sym__string_content,
  [534] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    STATE(41), 1,
      sym_seq,
    ACTIONS(177), 2,
      anon_sym_EQ,
      anon_sym_LBRACE,
  [548] = 4,
    ACTIONS(160), 1,
      sym_comment,
    ACTIONS(181), 1,
      anon_sym_DQUOTE,
    STATE(38), 1,
      aux_sym_string_repeat1,
    ACTIONS(179), 2,
      sym_escaped,
      sym__string_content,
  [562] = 4,
    ACTIONS(160), 1,
      sym_comment,
    ACTIONS(183), 1,
      anon_sym_DQUOTE,
    STATE(32), 1,
      aux_sym_string_repeat1,
    ACTIONS(169), 2,
      sym_escaped,
      sym__string_content,
  [576] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(110), 1,
      anon_sym_LBRACE,
    ACTIONS(185), 1,
      anon_sym_EQ,
    STATE(19), 1,
      sym_map,
  [589] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(187), 2,
      anon_sym_EQ,
      anon_sym_LBRACE,
  [597] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(189), 2,
      anon_sym_EQ,
      anon_sym_LBRACE,
  [605] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(191), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(11)] = 0,
  [SMALL_STATE(12)] = 38,
  [SMALL_STATE(13)] = 61,
  [SMALL_STATE(14)] = 84,
  [SMALL_STATE(15)] = 107,
  [SMALL_STATE(16)] = 130,
  [SMALL_STATE(17)] = 153,
  [SMALL_STATE(18)] = 179,
  [SMALL_STATE(19)] = 205,
  [SMALL_STATE(20)] = 226,
  [SMALL_STATE(21)] = 247,
  [SMALL_STATE(22)] = 268,
  [SMALL_STATE(23)] = 289,
  [SMALL_STATE(24)] = 310,
  [SMALL_STATE(25)] = 331,
  [SMALL_STATE(26)] = 352,
  [SMALL_STATE(27)] = 373,
  [SMALL_STATE(28)] = 394,
  [SMALL_STATE(29)] = 415,
  [SMALL_STATE(30)] = 436,
  [SMALL_STATE(31)] = 457,
  [SMALL_STATE(32)] = 478,
  [SMALL_STATE(33)] = 492,
  [SMALL_STATE(34)] = 506,
  [SMALL_STATE(35)] = 520,
  [SMALL_STATE(36)] = 534,
  [SMALL_STATE(37)] = 548,
  [SMALL_STATE(38)] = 562,
  [SMALL_STATE(39)] = 576,
  [SMALL_STATE(40)] = 589,
  [SMALL_STATE(41)] = 597,
  [SMALL_STATE(42)] = 605,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_config, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_seq_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_seq_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_seq_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [44] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_seq_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_seq_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_seq_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_seq_repeat1, 2, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_config_repeat1, 2, 0, 0),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_config_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [60] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_config_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [63] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_config_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [66] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_config_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [69] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_config_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [72] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_config_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [75] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_config_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [80] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [88] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_config, 1, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [96] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [104] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_seq, 2, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_seq, 2, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_float, 1, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_float, 1, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_seq, 3, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_seq, 3, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__value, 1, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__value, 1, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_kv, 2, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_kv, 2, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bool, 1, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bool, 1, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tagged, 2, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tagged, 2, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_kv, 3, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_kv, 3, 0, 0),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map, 2, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_map, 2, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map, 3, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_map, 3, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [162] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [165] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__key, 1, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [171] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [175] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__key, 1, 0, 1),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [181] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [183] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tagged_key, 2, 0, 0),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tagged_key, 2, 0, 1),
  [191] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_mayfig(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "mayfig",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
